### ISSUE TITLE
Explore share manager instead

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share-target#2]
It might be worth while to explore a having a ShareManager, that is similar to the PushManager, where share registration can happen for a given Service Worker (given that you can have multiple service workers, you need to actually state which service worker should receive the share event). 

Thus, the manifest option probably won't work, because every service worker would receive the "share" event... leading to a lot of confusion.

**Comment by marcoscaceres** [comment]
Roughly, in index.html 
```JS
// The page
 async function doRegistration() {
   const reg = await navigator.serviceWorker.getRegistration();
   // Some way to register this as a target
   await reg.shareManager.requestRegistration({
      // Site details for Registration UI
      // icons, etc. could maybe use manifest's icons without needing 
      // to declare again... 
   });
}().catch(err => console.err("Something went wrong", err))
```

And, as discussed already, SW.js

```JS
// The service worker
addEventListener("share", ( {url} )=> {
   // do some magic with the clients (e.g., get the focused one - or pop up a window)
});
```

**Comment by marcoscaceres** [comment]
Could you provide a bit more detail about what you see as the use case for that? What would an indexing/search engine do with that information? Right now, it feels like a "nice to have" feature to me, but not critical.

**Comment by ewilligers** [comment]
This issue is obsolete, now that we settled during the TAG review on receiving shares as GET or POST requests.
