### ISSUE TITLE
Share binary data

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [WICG/web-share-target#29]
Is it possible to receive binary data (e.g. image file) using this API? If yes, how? Or only text data is supported?

E.g. user adds SVGOMG PWA (https://jakearchibald.github.io/svgomg/) to the home screen using Chrome on Android and want to open *.svg files using the installed WebAPK.

**Comment by josephfrazier** [comment]
I'm also interested in this. A potential implementation could simply use a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) as the `url` value, right?

**Comment by ewilligers** [comment]
#53 describes how we propose to share files: POST requests with multipart/form-data.

This won't be in the initial version.

**Comment by josephfrazier** [comment]
Thanks for the update, @ewilligers! I'll follow along over there

**Comment by mgiuca** [comment]
This is now supported in the Level 2 spec:
https://wicg.github.io/web-share-target/level-2/

It's being implemented in Chrome (not rolled out yet) but the spec side is done.
