### ISSUE TITLE
Probably don't need text around failure

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share-target#3]
For the purpose of just shopping the proposal around, we probably don't need the following because they are self evident: 

> A share fails if:
> - The handler had no registered service worker.
> - There was an error during service worker initialization.
> - There is no event handler for `share` events.
> - The event handler explicitly calls the event's `reject` method (either in the
>   event handler, or in the promise passed to the event's
>   [`waitUntil`](https://www.w3.org/TR/service-workers/#wait-until-method)
>   method).
> - The promise passed to `waitUntil` is rejected.

**Comment by kenchris** [comment]
So as your PR landed @marcoscaceres can you close this?
