### ISSUE TITLE
Reject method of ShareEvent

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share-target#4]
We probably don't need this either... at least, there is nothing like that anywhere else in the platform: 

``` JS
void reject(DOMException error);
```

A share error event, if one was to occur, would need its own "onshareerror" event handler, similar to other DOM APIs.

**Comment by kenchris** [comment]
As this is not in the spec now, can we close this?

**Comment by ewilligers** [comment]
Note that events are still in the explainer.

We might want to mention in the explainer that proposed Service Worker [launch events](https://docs.google.com/document/d/1jWLpNEFttyLTnxsHs15oT-Hn8I81N0cwUa3JjISoPV8/edit) provide a more general way to satisfy the use cases of share events.
