### ISSUE TITLE
Incorrect Behavior in Chrome 72

### ISSUE THREAD

**Issue by VioletPixel** [WICG/web-share-target#75]
This API is broken in Chrome 72 on Android.  The value of the`url` parameter is always blank and the value of the `text` parameter contains the URL.  The `title` parameter seems to work just fine though!

<img width="352" alt="issue" src="https://user-images.githubusercontent.com/6766849/49332957-54ee2880-f56b-11e8-9fbe-7d8d9c92cdf0.png">

**Comment by glennhartmann** [comment]
Hi! Thanks for the report.

I'm not an authority on this repo, but I believe its purpose is to discuss the specification itself, and not any particular implementation.

Generally it's best to file Chrome implementation bugs (including Chrome for Android bugs) at http://crbug.com.

For now I've copied this into the Chromium bug tracker (I filed it as two bugs, but we may end up merging them).

http://crbug.com/914821, http://crbug.com/914822
