### ISSUE TITLE
ShareTargetFiles.accept shouldn't allow extensions

### ISSUE THREAD

**Issue by mounirlamouri** [WICG/web-share-target#76]
See: https://wicg.github.io/web-share-target/level-2/#sharetargetfiles-and-its-members 

This is copying the accept property from HTML forms but HTML forms came with years of legacy. The web has moved on and we use MIME Type instead of file extensions. We shouldn't encourage using file extensions.

**Comment by ewilligers** [comment]
#74 and #76 are the same issue.

**Comment by mounirlamouri** [comment]
Oups, thanks :)
