### ISSUE TITLE
Intent to migrate to WebApps WG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share-target#85]
We are interested on the Mozilla side in prototyping the Web Share spec. We are primarily looking at prototyping for Fenix. https://github.com/mozilla-mobile/fenix/issues/5783

Related Gecko bug for that will link to DOM/Manifest work:
 https://bugzilla.mozilla.org/show_bug.cgi?id=1476515

@NotWoods and I will be deep diving into the spec over coming weeks, so will likely have questions, comments, suggestions, and changes. 

As we have two interested implementers, we'd like to see the spec move into the WebApps WG for formal standardization.  The spec is within the WebAppsWG charter, section 2.2: 
https://www.w3.org/2019/05/webapps-charter.html#deliverables  

@mgiuca, @ericwilligers, I could use some help with:
https://github.com/WICG/admin/blob/gh-pages/intent-to-migrate.md

And then we can transfer this over 🎉

**Comment by mgiuca** [comment]
I started a new ticket since we want the survey to be in the text of the issue. See #87.
