### ISSUE TITLE
Support for custom protocols in share target

### ISSUE THREAD

**Issue by AStove** [WICG/web-share-target#90]
One limitation I'm facing is, imagine a SPA that is connected to a backend with a websocket. This application is intended to run as a single instance. It's in a state that cannot be simply created again in a new instance. When using a share target, it always opens a new instance, which is undesirable in this case.

Expanding the navigational scope of share target action to include [custom protocols](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-registerprotocolhandler) could be a solution. That way the running instance of the app could perhaps pick up the called share target action.

This is all a bit speculative though, I'm not sure it would actually work or be a good idea.

```
"share_target": {
  "action": "myapp://mydomain.com/share",
  "method": "GET",
  "params": {
    "title": "title",
    "text": "text",
    "url": "url"
  }
}
```

**Comment by AStove** [comment]
Or perhaps to not expand the scope too much, just change the protocol:
```
"share_target": {
  "protocol": "myapp",
  "action": "/share",
  "method": "GET",
  "params": {
    "title": "title",
    "text": "text",
    "url": "url"
  }
}
```

Results in a call to `myapp://mydomain.com/share`

**Comment by mgiuca** [comment]
I think this is out of scope of Web Share Target. There's a feature request for [protocol handlers to be registerable from within the manifest](https://github.com/w3c/manifest/issues/846).
